# You can use this file to easily send requests to your API.
# Prerequisite: humao.rest-client Vscode plugin (already present on codespace)
# High-level overview of REST API concepts used here: https://www.packtpub.com/en-us/learning/how-to-tutorials/what-are-rest-verbs-and-status-codes-tutorial

# TIP: Run requests in order - later requests reference IDs from earlier responses


# ==========================================
# User Controller Endpoints
# ==========================================

### Get all users
GET http://localhost:8080/api/users

### Create a new user (run this to populate variables for other requests)
# @name createUser
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Jean Valjean",
    "email": "prisoner24601@france.fr",
    "phone": "+40712345678"
}

### Get user by ID (uses ID from createUser response)
GET http://localhost:8080/api/users/{{createUser.response.body.id}}

### Get user by phone (uses phone from createUser response)
GET http://localhost:8080/api/users/by-phone?phone={{createUser.response.body.phone}}

### Update user contact (PUT)
PUT http://localhost:8080/api/users/{{createUser.response.body.id}}
Content-Type: application/json

{
    "email": "newemail@france.fr",
    "phone": "+40787654321"
}

### Change user name (PATCH)
PATCH http://localhost:8080/api/users/{{createUser.response.body.id}}/name
Content-Type: application/json

{
    "name": "Monsieur le Maire"
}

### Delete user
DELETE http://localhost:8080/api/users/{{createUser.response.body.id}}


# ==========================================
# Todo Controller Endpoints
# ==========================================

### Create a new todo (run this after createUser to populate variables)
# @name createTodo
POST http://localhost:8080/api/todos
Content-Type: application/json

{
    "description": "Rescue Cosette from the Thénardiers",
    "assigneeEmail": "{{createUser.response.body.email}}"
}

### Get todos by assignee email
GET http://localhost:8080/api/todos?assigneeEmail={{createUser.response.body.email}}

### Get todo by ID (uses ID from createTodo response)
GET http://localhost:8080/api/todos/{{createTodo.response.body.id}}

### Mark todo as done
PATCH http://localhost:8080/api/todos/{{createTodo.response.body.id}}/done
Content-Type: application/json

true

### Assign todo to another user
# Note: You'll need another user to exist for this to work

### Try to create user with duplicate phone (should fail with 400)
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Duplicate Phone",
    "email": "duplicate@example.com",
    "phone": "+40712345678"
}

### Try to create user with invalid data (should fail with 400)
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "",
    "email": "invalid-email",
    "phone": "123"
}

### Try to update contact with same data (should fail with 400)
PUT http://localhost:8080/api/users/69b864479eacf372f5926b47
Content-Type: application/json

{
    "email": "frodo@theshire.me",
    "phone": "+40712345678"
}

### Try to change name to same name (should fail with 400)
PATCH http://localhost:8080/api/users/69b864479eacf372f5926b47/name
Content-Type: application/json

{
    "name": "Frodo Baggins"
}
PATCH http://localhost:8080/api/todos/{{createTodo.response.body.id}}/assignee
Content-Type: application/json

{
    "newAssigneeEmail": "frodo@theshire.me"
}

### Edit todo description
PATCH http://localhost:8080/api/todos/{{createTodo.response.body.id}}/description
Content-Type: application/json

{
    "description": "Escape from Inspector Javert"
}


# ==========================================
# Cleanup (run these last)
# ==========================================

### Delete todo
DELETE http://localhost:8080/api/todos/{{createTodo.response.body.id}}

### Delete user
DELETE http://localhost:8080/api/users/{{createUser.response.body.id}}
