local counter = 0

wrk.method = "POST"
wrk.headers["Content-Type"] = "application/json"

request = function()
  counter = counter + 1
  local day = (counter % 20) + 1
  local hour = 8 + (counter % 9)
  local minute = (counter % 2) * 30
  local timestamp = string.format("2027-05-%02dT%02d:%02d:00", day, hour, minute)

  local body = string.format([[{
    "customerName":"Load Test %d",
    "customerEmail":"loadtest%d@example.com",
    "customerPhone":"+407000%05d",
    "vehicleBrand":"Dacia",
    "vehicleModel":"Duster",
    "vehicleRegistrationNumber":"B-%03d-LT",
    "serviceType":"Test drive",
    "appointmentAt":"%s",
    "notes":"generated by wrk performance test"
  }]], counter, counter, counter, counter % 999, timestamp)

  return wrk.format(nil, nil, nil, body)
end
