package ro.unibuc.prodeng.service;

import java.util.List;
import java.util.Locale;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.request.UpdateUserRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    public List<UserResponse> getAllUsers() {
        return userRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    public List<UserResponse> searchUsersByName(String nameQuery) {
        String normalizedQuery = normalizeName(nameQuery);
        return userRepository.findByNameContainingIgnoreCase(normalizedQuery).stream()
                .map(this::toResponse)
                .toList();
    }

    public UserResponse getUserById(String id) throws EntityNotFoundException {
        UserEntity user = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(user);
    }

    public UserEntity getUserEntityById(String id) throws EntityNotFoundException {
        return userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public UserResponse createUser(CreateUserRequest request) {
        String normalizedName = normalizeName(request.name());
        String normalizedEmail = normalizeEmail(request.email());
        String normalizedPhone = normalizePhone(request.phone());
        validateUniqueContact(null, normalizedEmail, normalizedPhone);

        UserEntity user = new UserEntity(
                null, // ID will be generated by the repository
                normalizedName,
                normalizedEmail,
                normalizedPhone
        );
        UserEntity saved = userRepository.save(user);
        return toResponse(saved);
    }

    public UserResponse updateUser(String id, UpdateUserRequest request) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));

        String normalizedName = normalizeName(request.name());
        String normalizedEmail = normalizeEmail(request.email());
        String normalizedPhone = normalizePhone(request.phone());

        if (existing.name().equals(normalizedName)
                && existing.email().equals(normalizedEmail)
                && existing.phone().equals(normalizedPhone)) {
            throw new IllegalArgumentException("Updated customer data is the same as current");
        }

        validateUniqueContact(existing.id(), normalizedEmail, normalizedPhone);

        UserEntity updated = new UserEntity(existing.id(), normalizedName, normalizedEmail, normalizedPhone);
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public UserResponse changeName(String id, String newName) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));

        String normalizedName = normalizeName(newName);
        if (existing.name().equals(normalizedName)) {
            throw new IllegalArgumentException("New name is the same as current name");
        }

        UserEntity updated = new UserEntity(existing.id(), normalizedName, existing.email(), existing.phone());
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public UserResponse changeContact(String id, String newEmail, String newPhone) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));

        String normalizedEmail = normalizeEmail(newEmail);
        String normalizedPhone = normalizePhone(newPhone);

        if (existing.email().equals(normalizedEmail) && existing.phone().equals(normalizedPhone)) {
            throw new IllegalArgumentException("New contact information is the same as current");
        }

        validateUniqueContact(existing.id(), normalizedEmail, normalizedPhone);

        UserEntity updated = new UserEntity(existing.id(), existing.name(), normalizedEmail, normalizedPhone);
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public void deleteUser(String id) throws EntityNotFoundException {
        if (!userRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        // TODO: Check if user has active purchases
        // For now, assume no active purchases
        boolean hasActivePurchases = false; // Placeholder
        if (hasActivePurchases) {
            throw new IllegalStateException("Cannot delete user with active purchases");
        }
        userRepository.deleteById(id);
    }

    public UserResponse getUserByEmail(String email) throws EntityNotFoundException {
        String normalizedEmail = normalizeEmail(email);
        UserEntity user = userRepository.findByEmail(normalizedEmail)
                .orElseThrow(() -> new EntityNotFoundException(email));
        return toResponse(user);
    }

    public UserEntity getUserEntityByEmail(String email) throws EntityNotFoundException {
        String normalizedEmail = normalizeEmail(email);
        return userRepository.findByEmail(normalizedEmail)
                .orElseThrow(() -> new EntityNotFoundException(email));
    }

    public UserResponse getUserByPhone(String phone) throws EntityNotFoundException {
        String normalizedPhone = normalizePhone(phone);
        UserEntity user = userRepository.findByPhone(normalizedPhone)
                .orElseThrow(() -> new EntityNotFoundException(phone));
        return toResponse(user);
    }

    private void validateUniqueContact(String currentUserId, String email, String phone) {
        Optional<UserEntity> existingByEmail = userRepository.findByEmail(email);
        if (existingByEmail.isPresent() && !existingByEmail.get().id().equals(currentUserId)) {
            throw new IllegalArgumentException("Email already exists: " + email);
        }

        Optional<UserEntity> existingByPhone = userRepository.findByPhone(phone);
        if (existingByPhone.isPresent() && !existingByPhone.get().id().equals(currentUserId)) {
            throw new IllegalArgumentException("Phone already exists: " + phone);
        }
    }

    private String normalizeName(String name) {
        return name.trim().replaceAll("\\s+", " ");
    }

    private String normalizeEmail(String email) {
        return email.trim().toLowerCase(Locale.ROOT);
    }

    private String normalizePhone(String phone) {
        return phone.trim().replaceAll("[\\s\\-\\(\\)]", "");
    }

    private UserResponse toResponse(UserEntity user) {
        return new UserResponse(
                user.id(),
                user.name(),
                user.email(),
                user.phone()
        );
    }
}
