package ro.unibuc.prodeng.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import ro.unibuc.prodeng.model.UserEntity;
import ro.unibuc.prodeng.repository.UserRepository;
import ro.unibuc.prodeng.request.CreateUserRequest;
import ro.unibuc.prodeng.response.UserResponse;
import ro.unibuc.prodeng.exception.EntityNotFoundException;

@Service
public class UserService {

    @Autowired
    private UserRepository userRepository;

    public List<UserResponse> getAllUsers() {
        return userRepository.findAll().stream()
                .map(this::toResponse)
                .toList();
    }

    public UserResponse getUserById(String id) throws EntityNotFoundException {
        UserEntity user = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        return toResponse(user);
    }

    public UserEntity getUserEntityById(String id) throws EntityNotFoundException {
        return userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
    }

    public UserResponse createUser(CreateUserRequest request) {
        if (userRepository.findByEmail(request.email()).isPresent()) {
            throw new IllegalArgumentException("Email already exists: " + request.email());
        }
        if (userRepository.findByPhone(request.phone()).isPresent()) {
            throw new IllegalArgumentException("Phone already exists: " + request.phone());
        }
        UserEntity user = new UserEntity(
                null, // ID will be generated by the repository
                request.name(),
                request.email(),
                request.phone()
        );
        UserEntity saved = userRepository.save(user);
        return toResponse(saved);
    }

    public UserResponse changeName(String id, String newName) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        if (existing.name().equals(newName)) {
            throw new IllegalArgumentException("New name is the same as current name");
        }
        UserEntity updated = new UserEntity(existing.id(), newName, existing.email(), existing.phone());
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public UserResponse changeContact(String id, String newEmail, String newPhone) throws EntityNotFoundException {
        UserEntity existing = userRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(id));
        if (existing.email().equals(newEmail) && existing.phone().equals(newPhone)) {
            throw new IllegalArgumentException("New contact information is the same as current");
        }
        if (!existing.email().equals(newEmail) && userRepository.findByEmail(newEmail).isPresent()) {
            throw new IllegalArgumentException("Email already exists: " + newEmail);
        }
        if (!existing.phone().equals(newPhone) && userRepository.findByPhone(newPhone).isPresent()) {
            throw new IllegalArgumentException("Phone already exists: " + newPhone);
        }
        UserEntity updated = new UserEntity(existing.id(), existing.name(), newEmail, newPhone);
        UserEntity saved = userRepository.save(updated);
        return toResponse(saved);
    }

    public void deleteUser(String id) throws EntityNotFoundException {
        if (!userRepository.existsById(id)) {
            throw new EntityNotFoundException(id);
        }
        // TODO: Check if user has active purchases
        // For now, assume no active purchases
        boolean hasActivePurchases = false; // Placeholder
        if (hasActivePurchases) {
            throw new IllegalStateException("Cannot delete user with active purchases");
        }
        userRepository.deleteById(id);
    }

    public UserResponse getUserByEmail(String email) throws EntityNotFoundException {
        UserEntity user = userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email));
        return toResponse(user);
    }

    public UserEntity getUserEntityByEmail(String email) throws EntityNotFoundException {
        return userRepository.findByEmail(email)
                .orElseThrow(() -> new EntityNotFoundException(email));
    }

    public UserResponse getUserByPhone(String phone) throws EntityNotFoundException {
        UserEntity user = userRepository.findByPhone(phone)
                .orElseThrow(() -> new EntityNotFoundException(phone));
        return toResponse(user);
    }

    private UserResponse toResponse(UserEntity user) {
        return new UserResponse(
                user.id(),
                user.name(),
                user.email(),
                user.phone()
        );
    }
}
